ALTER TABLE users
  ADD COLUMN IF NOT EXISTS rating numeric(3,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rating_count int NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS balance_tokens bigint NOT NULL DEFAULT 0;
